/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiQaRouteImport } from './routes/ai/qa'
import { Route as AiGoalRouteImport } from './routes/ai/goal'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiQaRoute = AiQaRouteImport.update({
  id: '/ai/qa',
  path: '/ai/qa',
  getParentRoute: () => rootRouteImport,
} as any)
const AiGoalRoute = AiGoalRouteImport.update({
  id: '/ai/goal',
  path: '/ai/goal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai/goal': typeof AiGoalRoute
  '/ai/qa': typeof AiQaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai/goal': typeof AiGoalRoute
  '/ai/qa': typeof AiQaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai/goal': typeof AiGoalRoute
  '/ai/qa': typeof AiQaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/ai/goal' | '/ai/qa'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/ai/goal' | '/ai/qa'
  id: '__root__' | '/' | '/about' | '/ai/goal' | '/ai/qa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiGoalRoute: typeof AiGoalRoute
  AiQaRoute: typeof AiQaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/qa': {
      id: '/ai/qa'
      path: '/ai/qa'
      fullPath: '/ai/qa'
      preLoaderRoute: typeof AiQaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/goal': {
      id: '/ai/goal'
      path: '/ai/goal'
      fullPath: '/ai/goal'
      preLoaderRoute: typeof AiGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiGoalRoute: AiGoalRoute,
  AiQaRoute: AiQaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
